-- PermitFlow reference and staff data
-- Depends on 001_schema.sql
--
-- This file seeds only data that a real deployment would configure once: reference
-- tables, the SLA policies, the municipal holiday calendar, and department staff.
-- Sample cases are generated by scripts/seed_cases.py, which drives the process engine
-- so the resulting history is consistent with the rules rather than hand-written.

BEGIN;

-- ---------------------------------------------------------------------------
-- Zoning districts
-- ---------------------------------------------------------------------------

INSERT INTO zoning_district (code, name, category, description) VALUES
    ('R-60',  'Residential, 6,000 sq ft minimum lot',  'residential', 'Single family detached, moderate density'),
    ('R-90',  'Residential, 9,000 sq ft minimum lot',  'residential', 'Single family detached, low density'),
    ('R-200', 'Residential, 20,000 sq ft minimum lot', 'residential', 'Single family detached, large lot'),
    ('RT-8',  'Residential townhouse',                 'residential', 'Attached dwellings up to 8 units per acre'),
    ('C-1',   'Neighborhood commercial',               'commercial',  'Local retail and service'),
    ('C-2',   'General commercial',                    'commercial',  'Regional retail, office, hospitality'),
    ('I-1',   'Light industrial',                      'industrial',  'Warehousing, light manufacturing'),
    ('MXD',   'Mixed use district',                    'mixed',       'Residential above ground floor commercial'),
    ('PRD',   'Planned redevelopment district',        'special',     'Subject to an approved development plan');

-- ---------------------------------------------------------------------------
-- Permit types
-- Council standard days come from the 2024 service standard resolution: 20 business
-- days for residential, 30 for commercial. Accessory structures were set at 15 by
-- department policy rather than by the council.
-- ---------------------------------------------------------------------------

INSERT INTO permit_type (code, name, category, council_standard_days) VALUES
    ('BLD-RES-NEW',  'Residential new construction',              'residential', 20),
    ('BLD-RES-ALT',  'Residential alteration or addition',        'residential', 20),
    ('BLD-RES-ACC',  'Residential accessory structure',           'residential', 15),
    ('BLD-COM-NEW',  'Commercial new construction',               'commercial',  30),
    ('BLD-COM-ALT',  'Commercial alteration or tenant fit-out',   'commercial',  30);

-- ---------------------------------------------------------------------------
-- Disciplines
-- ---------------------------------------------------------------------------

INSERT INTO discipline (code, name, description) VALUES
    ('ZONING',        'Zoning review',        'Setbacks, lot coverage, height, use, parking'),
    ('STRUCTURAL',    'Structural review',    'Load paths, foundations, framing, seismic and wind'),
    ('FIRE',          'Fire and life safety', 'Egress, suppression, alarm, occupancy load'),
    ('ENVIRONMENTAL', 'Environmental review', 'Stormwater, erosion control, floodplain, tree canopy');

-- ---------------------------------------------------------------------------
-- Document types
-- ---------------------------------------------------------------------------

INSERT INTO document_type (code, name, description) VALUES
    ('SITE_PLAN',        'Site plan',                 'Scaled plan showing structures, setbacks, and lot lines'),
    ('FLOOR_PLAN',       'Floor plan',                'Dimensioned plan of each level'),
    ('ELEVATIONS',       'Elevation drawings',        'Exterior elevations with heights'),
    ('STRUCTURAL_CALC',  'Structural calculations',   'Sealed calculations from a licensed engineer'),
    ('ENERGY_FORM',      'Energy compliance form',    'Demonstrates compliance with the adopted energy code'),
    ('STORMWATER_PLAN',  'Stormwater management plan','Required where impervious area increases materially'),
    ('FIRE_PLAN',        'Fire protection plan',      'Suppression, alarm, and egress plan'),
    ('SURVEY',           'Boundary survey',           'Sealed survey by a licensed surveyor'),
    ('GEOTECH',          'Geotechnical report',       'Soils investigation and foundation recommendation'),
    ('CONTRACTOR_AFF',   'Contractor affidavit',      'Signed statement of license and workers compensation');

-- ---------------------------------------------------------------------------
-- Required document checklist rules (FR-04)
-- min_valuation gates a document behind a project size, which is how the department
-- avoids demanding sealed structural calculations for a rear deck.
-- ---------------------------------------------------------------------------

INSERT INTO permit_type_document (permit_type_code, document_type_code, required, min_valuation) VALUES
    -- Residential new construction
    ('BLD-RES-NEW', 'SITE_PLAN',       true,  NULL),
    ('BLD-RES-NEW', 'FLOOR_PLAN',      true,  NULL),
    ('BLD-RES-NEW', 'ELEVATIONS',      true,  NULL),
    ('BLD-RES-NEW', 'SURVEY',          true,  NULL),
    ('BLD-RES-NEW', 'ENERGY_FORM',     true,  NULL),
    ('BLD-RES-NEW', 'STRUCTURAL_CALC', true,  NULL),
    ('BLD-RES-NEW', 'CONTRACTOR_AFF',  true,  NULL),
    ('BLD-RES-NEW', 'STORMWATER_PLAN', true,  250000.00),
    ('BLD-RES-NEW', 'GEOTECH',         true,  500000.00),

    -- Residential alteration
    ('BLD-RES-ALT', 'SITE_PLAN',       true,  NULL),
    ('BLD-RES-ALT', 'FLOOR_PLAN',      true,  NULL),
    ('BLD-RES-ALT', 'CONTRACTOR_AFF',  true,  NULL),
    ('BLD-RES-ALT', 'ENERGY_FORM',     true,  50000.00),
    ('BLD-RES-ALT', 'STRUCTURAL_CALC', true,  75000.00),

    -- Residential accessory structure
    ('BLD-RES-ACC', 'SITE_PLAN',       true,  NULL),
    ('BLD-RES-ACC', 'ELEVATIONS',      true,  NULL),
    ('BLD-RES-ACC', 'CONTRACTOR_AFF',  true,  NULL),

    -- Commercial new construction
    ('BLD-COM-NEW', 'SITE_PLAN',       true,  NULL),
    ('BLD-COM-NEW', 'FLOOR_PLAN',      true,  NULL),
    ('BLD-COM-NEW', 'ELEVATIONS',      true,  NULL),
    ('BLD-COM-NEW', 'SURVEY',          true,  NULL),
    ('BLD-COM-NEW', 'STRUCTURAL_CALC', true,  NULL),
    ('BLD-COM-NEW', 'FIRE_PLAN',       true,  NULL),
    ('BLD-COM-NEW', 'STORMWATER_PLAN', true,  NULL),
    ('BLD-COM-NEW', 'ENERGY_FORM',     true,  NULL),
    ('BLD-COM-NEW', 'CONTRACTOR_AFF',  true,  NULL),
    ('BLD-COM-NEW', 'GEOTECH',         true,  1000000.00),

    -- Commercial alteration
    ('BLD-COM-ALT', 'FLOOR_PLAN',      true,  NULL),
    ('BLD-COM-ALT', 'FIRE_PLAN',       true,  NULL),
    ('BLD-COM-ALT', 'CONTRACTOR_AFF',  true,  NULL),
    ('BLD-COM-ALT', 'STRUCTURAL_CALC', true,  150000.00),
    ('BLD-COM-ALT', 'ENERGY_FORM',     true,  100000.00);

-- ---------------------------------------------------------------------------
-- Base discipline routing (FR-07)
-- always_required disciplines are routed unconditionally. The others are candidates the
-- triage step may recommend based on the scope of work, subject to clerk confirmation.
-- ---------------------------------------------------------------------------

INSERT INTO permit_type_discipline (permit_type_code, discipline_code, always_required) VALUES
    ('BLD-RES-NEW', 'ZONING',        true),
    ('BLD-RES-NEW', 'STRUCTURAL',    true),
    ('BLD-RES-NEW', 'ENVIRONMENTAL', false),

    ('BLD-RES-ALT', 'ZONING',        true),
    ('BLD-RES-ALT', 'STRUCTURAL',    true),
    ('BLD-RES-ALT', 'ENVIRONMENTAL', false),

    ('BLD-RES-ACC', 'ZONING',        true),
    ('BLD-RES-ACC', 'STRUCTURAL',    false),

    ('BLD-COM-NEW', 'ZONING',        true),
    ('BLD-COM-NEW', 'STRUCTURAL',    true),
    ('BLD-COM-NEW', 'FIRE',          true),
    ('BLD-COM-NEW', 'ENVIRONMENTAL', true),

    ('BLD-COM-ALT', 'ZONING',        true),
    ('BLD-COM-ALT', 'FIRE',          true),
    ('BLD-COM-ALT', 'STRUCTURAL',    false),
    ('BLD-COM-ALT', 'ENVIRONMENTAL', false);

-- ---------------------------------------------------------------------------
-- SLA policies
-- The phase allowances sum to the council standard for each permit type.
-- Residential: 3 + 14 + 3 = 20. Accessory: 2 + 11 + 2 = 15. Commercial: 4 + 22 + 4 = 30.
-- ---------------------------------------------------------------------------

INSERT INTO sla_policy (permit_type_code, phase, discipline_code, allowance_days) VALUES
    ('BLD-RES-NEW', 'INTAKE_SCREENING', NULL, 3),
    ('BLD-RES-NEW', 'REVIEW_TASK',      NULL, 14),
    ('BLD-RES-NEW', 'PENDING_DECISION', NULL, 3),

    ('BLD-RES-ALT', 'INTAKE_SCREENING', NULL, 3),
    ('BLD-RES-ALT', 'REVIEW_TASK',      NULL, 14),
    ('BLD-RES-ALT', 'PENDING_DECISION', NULL, 3),

    ('BLD-RES-ACC', 'INTAKE_SCREENING', NULL, 2),
    ('BLD-RES-ACC', 'REVIEW_TASK',      NULL, 11),
    ('BLD-RES-ACC', 'PENDING_DECISION', NULL, 2),

    ('BLD-COM-NEW', 'INTAKE_SCREENING', NULL, 4),
    ('BLD-COM-NEW', 'REVIEW_TASK',      NULL, 22),
    ('BLD-COM-NEW', 'PENDING_DECISION', NULL, 4),

    ('BLD-COM-ALT', 'INTAKE_SCREENING', NULL, 4),
    ('BLD-COM-ALT', 'REVIEW_TASK',      NULL, 22),
    ('BLD-COM-ALT', 'PENDING_DECISION', NULL, 4);

-- Environmental review on commercial new construction gets a longer allowance because
-- stormwater modelling is slower than the other disciplines. A discipline-specific policy
-- overrides the NULL-discipline default for that phase.
INSERT INTO sla_policy (permit_type_code, phase, discipline_code, allowance_days) VALUES
    ('BLD-COM-NEW', 'REVIEW_TASK', 'ENVIRONMENTAL', 25);

-- ---------------------------------------------------------------------------
-- Municipal holiday calendar
-- Observed dates. Where a holiday falls on a weekend the observed weekday is listed,
-- because the SLA clock only ever looks at weekdays.
-- ---------------------------------------------------------------------------

INSERT INTO holiday (holiday_date, name) VALUES
    ('2025-01-01', 'New Year''s Day'),
    ('2025-01-20', 'Martin Luther King Jr. Day'),
    ('2025-02-17', 'Presidents Day'),
    ('2025-05-26', 'Memorial Day'),
    ('2025-06-19', 'Juneteenth'),
    ('2025-07-04', 'Independence Day'),
    ('2025-09-01', 'Labor Day'),
    ('2025-10-13', 'Indigenous Peoples Day'),
    ('2025-11-11', 'Veterans Day'),
    ('2025-11-27', 'Thanksgiving Day'),
    ('2025-11-28', 'Day after Thanksgiving'),
    ('2025-12-25', 'Christmas Day'),

    ('2026-01-01', 'New Year''s Day'),
    ('2026-01-19', 'Martin Luther King Jr. Day'),
    ('2026-02-16', 'Presidents Day'),
    ('2026-05-25', 'Memorial Day'),
    ('2026-06-19', 'Juneteenth'),
    ('2026-07-03', 'Independence Day (observed)'),
    ('2026-09-07', 'Labor Day'),
    ('2026-10-12', 'Indigenous Peoples Day'),
    ('2026-11-11', 'Veterans Day'),
    ('2026-11-26', 'Thanksgiving Day'),
    ('2026-11-27', 'Day after Thanksgiving'),
    ('2026-12-25', 'Christmas Day'),

    ('2027-01-01', 'New Year''s Day');

-- ---------------------------------------------------------------------------
-- Department staff
-- Certification coverage is deliberately uneven. Environmental has two certified
-- reviewers and fire has two, which is what makes the assignment tests meaningful and
-- what produced pain point P4 in the first place.
-- ---------------------------------------------------------------------------

INSERT INTO reviewer (id, username, full_name, email, role, active) VALUES
    ('11111111-1111-4111-8111-000000000001', 'dhollis',  'Denise Hollis',   'dhollis@rivermont.gov',  'supervisor',   true),
    ('11111111-1111-4111-8111-000000000002', 'mcarrero', 'Marisol Carrero', 'mcarrero@rivermont.gov', 'intake_clerk', true),
    ('11111111-1111-4111-8111-000000000003', 'jtakeda',  'Jun Takeda',      'jtakeda@rivermont.gov',  'intake_clerk', true),
    ('11111111-1111-4111-8111-000000000004', 'rokafor',  'Ruth Okafor',     'rokafor@rivermont.gov',  'reviewer',     true),
    ('11111111-1111-4111-8111-000000000005', 'pvasquez', 'Paulo Vasquez',   'pvasquez@rivermont.gov', 'reviewer',     true),
    ('11111111-1111-4111-8111-000000000006', 'clindgren','Cara Lindgren',   'clindgren@rivermont.gov','reviewer',     true),
    ('11111111-1111-4111-8111-000000000007', 'abassett', 'Andre Bassett',   'abassett@rivermont.gov', 'reviewer',     true),
    ('11111111-1111-4111-8111-000000000008', 'nmalik',   'Nadia Malik',     'nmalik@rivermont.gov',   'reviewer',     true),
    ('11111111-1111-4111-8111-000000000009', 'gferris',  'Glen Ferris',     'gferris@rivermont.gov',  'reviewer',     true),
    ('11111111-1111-4111-8111-00000000000a', 'tbrandt',  'Tomas Brandt',    'tbrandt@rivermont.gov',  'reviewer',     false);

INSERT INTO reviewer_discipline (reviewer_id, discipline_code, certified_on) VALUES
    ('11111111-1111-4111-8111-000000000004', 'ZONING',        '2019-03-11'),
    ('11111111-1111-4111-8111-000000000004', 'ENVIRONMENTAL', '2022-08-01'),
    ('11111111-1111-4111-8111-000000000005', 'ZONING',        '2021-06-14'),
    ('11111111-1111-4111-8111-000000000006', 'STRUCTURAL',    '2017-01-09'),
    ('11111111-1111-4111-8111-000000000007', 'STRUCTURAL',    '2020-10-05'),
    ('11111111-1111-4111-8111-000000000007', 'FIRE',          '2023-02-20'),
    ('11111111-1111-4111-8111-000000000008', 'FIRE',          '2018-05-07'),
    ('11111111-1111-4111-8111-000000000009', 'ENVIRONMENTAL', '2016-09-19'),
    -- Tomas is certified but inactive. Assignment must skip him, which US-09 tests.
    ('11111111-1111-4111-8111-00000000000a', 'ZONING',        '2015-04-02'),
    ('11111111-1111-4111-8111-00000000000a', 'STRUCTURAL',    '2015-04-02');

COMMIT;
